### ISSUE TITLE
When dragging a spell onto the inventory for an actor, we'd like the wand, potion, or scroll text to be prepended to the spell description -- rather than replace it.

### ISSUE THREAD

**Issue by adventuremagic123** [SvenWerlen/fvtt-loot-sheet-npc-pf1#1]
We really like this module.  Rather than having the description for a wand, potion, or scroll replace the spell description, we'd like it to be prepended to the spell description.  We need the spell description to still be there.

**Comment by SvenWerlen** [comment]
Thank you for reporting this.
The drag-and-drop behavior for spells is inherited from the system (pf1) and not specific to this module anymore. I recommend re-posting this request to https://gitlab.com/Furyspark/foundryvtt-pathfinder1
