### ISSUE TITLE
permission buttons not working

### ISSUE THREAD

**Issue by apetina** [SvenWerlen/fvtt-loot-sheet-npc-pf1#13]
Clicking on the buttons next to player name or in the buttons below players doesn't update the permissions. Permissions are only updated after refreshing Foundry.
Tested in a new world with only this module active.
Foundry version: 0.7.9
Pathfinder 1 version: 0.77.7

**Comment by SvenWerlen** [comment]
Thanks for reporting this. 
I can confirm this behavior when the token is linked to the actor (or when the sheet is opened from the actor itself)
I must investigate why this happens.

**Comment by SvenWerlen** [comment]
Fixed in version `1.9.0` (soon released)
