### ISSUE TITLE
Question, not an issue

### ISSUE THREAD

**Issue by Motara7** [SvenWerlen/fvtt-loot-sheet-npc-pf1#15]
- I have an actor called Party Treasure that is set to the PF1e loot sheet. All PCs have Observer permission to it.
- I have one PC who is like an assistant and I want them to be responsible for moving loot from defeated enemies/treasure parcels/etc.
- The problem is, I can't figure out a way for a player to be able to drag an item from a defeated enemy loot sheet to the party treasure. And if they use the loot item button, it just goes to their character sheet.

Is there a way I can make this work?

**Comment by SvenWerlen** [comment]
You could enable "dragging" and drag it on another sheet. However, it will duplicate the item and you'll have to remove it from the loot sheet. There is unfortunately no other way. You could also take it as a character and drop it on the party treasure but this means 2x more effort.
