### ISSUE TITLE
Request: 0.8.6 compatibility update

### ISSUE THREAD

**Issue by misterchristophertoo** [SvenWerlen/fvtt-loot-sheet-npc-pf1#19]
Just curious if there's a plan to update this mod for 0.8.x. Didn't see any mention of it anywhere and no one seemed to have asked.

**Comment by NorthernTempest** [comment]
Also looking for this

**Comment by SvenWerlen** [comment]
Version `2.1.1+` support 0.8.x. Please let me know if you still have issues with it.
