### ISSUE TITLE
Weightless currency is not valid for buying items

### ISSUE THREAD

**Issue by mkahvi** [SvenWerlen/fvtt-loot-sheet-npc-pf1#2]
Attempting to buy items from merchant loot sheet with only weightless currency on character, it claims the character has insufficient funds to buy with.

> PF1e System 0.76.6
> PF1e Loot Sheet 1.7.1

**Comment by SvenWerlen** [comment]
`v-1.9.0` will support buying from weightless currency. It empties first the default currency. If not sufficient, it removes from weightless currency. If character only has weightless currency, it will buy entirely from weightless currency.

Some rare usecases don't work and will end up with an error message. This is generally when the item cost is a fraction of gp (ex: 1.25).

I hope that this behavior corresponds to your expectations.
