### ISSUE TITLE
Sheet can not be closed

### ISSUE THREAD

**Issue by NickOfSon** [SvenWerlen/fvtt-loot-sheet-npc-pf1#21]
After a recent update when you choose LootSheet you can't close the sheet since button "close" not working I have either to disable module or change it to another sheet.

Foundry: 0.8.6
Pf1: 0.78.8
LootSheetNPCpf1: 2.1.0

**Comment by websterguy** [comment]
I also cannot close the sheet, but only when it is set to merchant mode. Loot mode works fine.

**Comment by Koalahund** [comment]
> I also cannot close the sheet, but only when it is set to merchant mode. Loot mode works fine.

Only happens for unlinked tokens in merchant mode for me. Linked tokens or opening the actor sheet directly in the actor tab cause no problems.

**Comment by NickOfSon** [comment]
Loot sheet works fine till adding a spell item from the compendium then it freezes. Merchant mode keeps always freezing even it's empty.
