### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Luisphigor** [SvenWerlen/fvtt-loot-sheet-npc-pf1#26]
Pls find attached italian translation file.
[it.zip](https://github.com/SvenWerlen/fvtt-loot-sheet-npc-pf1/files/7048162/it.zip)

Code to include in module.json file:
```
   {
      "lang": "it",
      "name": "Italiano",
      "path": "lang/it.json"
    },
```

I hope you'll include it in your next release. Thanks

**Comment by SvenWerlen** [comment]
Thank you for submitting these translations.
They have been integrated and will be included in the next release
