### ISSUE TITLE
Can't sell items from containers

### ISSUE THREAD

**Issue by mkahvi** [SvenWerlen/fvtt-loot-sheet-npc-pf1#3]
Selling items by dragging them from a container into a merchant loot sheet doesn't do anything.

> FVTT 0.7.7
> PF1e 0.76.6
> Loot Sheet 1.7.1

**Comment by SvenWerlen** [comment]
Version `1.9.0` has limited support for containers but doesn't support drag-and-drop from a container yet.

**Comment by SvenWerlen** [comment]
I'll close this issue for now because I don't plan to implement it for now (too busy with my other modules).
