### ISSUE TITLE
Buying items does not work if player does not have character selected.

### ISSUE THREAD

**Issue by mkahvi** [SvenWerlen/fvtt-loot-sheet-npc-pf1#5]
If player has no character selected (in player configuration) when they load in, such as due to controlling multiple characters, the buy option does not show up.

Strangely though, if player configures character selection and releases it after, the shop works fine, but only until they reload.

**Comment by mkahvi** [comment]
To clarify, this is caused by attempting to use `game.user.character` exclusively for finding relevant character.

Currently selected token (`canvas.tokens.controlled`) should be viable fallback solution.

**Comment by SvenWerlen** [comment]
I'm not sure how to implement this. The module needs to know for which token/actor the item was bought/looted.
That prerequisite is implemented at several places in the code. Probably complex to change. Feel free to reopen it if you really think that's a use case that should be supported.
