### ISSUE TITLE
Add option of infinite supply on merchant

### ISSUE THREAD

**Issue by mkahvi** [SvenWerlen/fvtt-loot-sheet-npc-pf1#6]
I'd like there to be an option to have infinite supply of one or more items on a merchant without just giving them millions of the items.

Alternatively don't remove the item once supply runs out, just leave them at 0 quantity and maybe hide them from players.

**Comment by SvenWerlen** [comment]
Implementation so far :
![image](https://user-images.githubusercontent.com/938060/107306765-7a342680-6a53-11eb-8b4c-87a2c0a95138.png)

Limitations :
* If GM sets infinity for loot (not merchant) and converts loot into gold, the real quantity (before set to infinity) will be converted

If you are ok with this implementation, I'll include in the next release.

**Comment by mkahvi** [comment]
Looks good. I can't spot anything to nitpick on.

**Comment by SvenWerlen** [comment]
Implemented in version `1.9.0` (soon released)
