### ISSUE TITLE
lootsheet not correctly adding item quantity. 

### ISSUE THREAD

**Issue by g1eagle** [SvenWerlen/fvtt-loot-sheet-npc-pf1#8]
Loot sheet stopped giving items quantity (rolls for it though) and the sheet now looks weird in latest version of foundryvtt. 
Console shows items being added 4 x item.. but item is crossed out on sheet.

**Comment by SvenWerlen** [comment]
Hi,
Can you confirm this problem still exists ? I cannot reproduce it.
If this is the case, which version of foundryvtt are you using?

**Comment by SvenWerlen** [comment]
Cannot reproduce
